# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: true

# Do not choose a language; we provide our own build tools.
language: generic

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/nakadi
  - $HOME/.gradle

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Install more recent docker-compose
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- if test -e $HOME/nakadi/.git; then (cd $HOME/nakadi && git pull); else git clone https://github.com/zalando/nakadi.git $HOME/nakadi; fi
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
# Download and unpack the stack executable
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Stop Postgres, since we will spin up our own dockerized Postgres
- sudo /etc/init.d/postgresql stop

install:
# Build dependencies
- stack --no-terminal --install-ghc build --test --only-dependencies

before_script:
- (cd $HOME/nakadi; TERM=dumb ./gradlew startNakadi)

after_script:
- (cd $HOME/nakadi; TERM=dumb ./gradlew stopNakadi)

script:
- TEST_NAKADI_ENDPOINT=http://localhost:8080/ stack --no-terminal build --test --haddock --no-haddock-deps --flag nakadi-client:devel
