resolver: lts-11.15
packages:
- '.'
extra-deps: [ async-2.2.1
            , lifted-async-0.10.0
            , async-timer-0.2.0.0
            , unliftio-0.2.4.0
            , safe-exceptions-0.1.7.0
            , resourcet-1.2.0
            , http-conduit-2.3.0
            , conduit-1.3.0
            , conduit-extra-1.3.0
            , cereal-conduit-0.8.0
            , stm-conduit-4.0.0
            , classy-prelude-1.4.0
            ]
flags: {}
extra-package-dbs: []
