resolver: lts-11.1
packages:
- '.'
extra-deps: [ async-2.2.1
            , lifted-async-0.10.0
            , async-timer-0.2.0.0
            , th-format-0.1.1.0
            ]
flags: {}
extra-package-dbs: []
